# Generated by Django 5.2.6 on 2025-09-17 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bocarella', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
