# Generated by Django 5.2.6 on 2025-09-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocarella', '0002_acompanamiento_extra_pizza_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Administrador')], default='usuario', max_length=10),
        ),
    ]
