# Generated by Django 5.2.6 on 2025-09-22 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocarella', '0002_rename_titulo_promocion_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='recibido_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil__rol': 'empleado'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Administrador'), ('empleado', 'Empleado')], default='usuario', max_length=10),
        ),
    ]
