# Generated by Django 5.2.6 on 2025-09-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocarella', '0003_orden_recibido_por_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado_cocina',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparacion', 'En preparación'), ('lista', 'Lista para salida')], default='pendiente', max_length=20),
        ),
    ]
